language: node_js
node_js:
  - 14.0.0

jobs:
  include:
    - stage: build
      script: npm build
    - stage: deploy
      script: echo "hello"
      if: branch = master

stages:
  - build
  - test
  - deploy
