language: node_js
node_js:
  - 14.0.0

jobs:
  include:
    - stage: build
      script: npm build
    - stage: test
      script: npm test

stages:
  - build
  - test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  keep_history: true
  on:
    branch: master
